# Generated by Django 4.1.13 on 2024-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_ordermodel_discount_ordermodel_shipping_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
